# Generated by Django 4.2.16 on 2024-10-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_course_imgae_course_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.AddField(
            model_name='course',
            name='free_part',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='full_course',
            field=models.TextField(blank=True),
        ),
    ]
