# Generated by Django 4.2.16 on 2024-10-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_course_image_course_free_part_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('full_course', models.TextField()),
                ('slug', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='full_course',
        ),
    ]
