# Generated by Django 4.2.16 on 2024-10-22 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_coursefull_remove_course_full_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefull',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='full_versions', to='courses.course'),
        ),
    ]
