# Generated by Django 4.2.16 on 2024-10-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_coursefull_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='full_course',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='CourseFull',
        ),
    ]
