# Generated by Django 4.2.16 on 2024-11-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='link_video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
