# Generated by Django 4.2.16 on 2024-11-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_course_link_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='expectation',
            field=models.TextField(blank=True),
        ),
    ]
